// Source of truth for provider brand marks.
// `npm run logos` fetches PNGs from Logo.dev into assets/logos/{slug}.png.
// Domains are tried first (most reliable); name lookups are fallbacks.

export const PROVIDER_LOGOS = {
  'OpenAI': { slug: 'openai', domains: ['openai.com'], names: ['OpenAI'] },
  'Anthropic': { slug: 'anthropic', domains: ['anthropic.com'], names: ['Anthropic'] },
  'Google Gemini': { slug: 'google', domains: ['google.com'], names: ['Google'] },
  'xAI / Grok': { slug: 'xai', domains: ['x.ai'], names: ['xAI'] },
  'Alibaba / Qwen': { slug: 'alibaba', domains: ['alibabacloud.com', 'alibaba.com'], names: ['Alibaba'] },
  'Moonshot AI / Kimi': { slug: 'moonshot', domains: ['kimi.com', 'moonshot.ai'], names: ['Moonshot AI', 'Kimi'] },
  'Zhipu AI / GLM': { slug: 'zhipu', domains: ['z.ai', 'zhipuai.cn'], names: ['Zhipu AI'] },
  'MiniMax': { slug: 'minimax', domains: ['minimax.io'], names: ['MiniMax'] },
  'DeepSeek': { slug: 'deepseek', domains: ['deepseek.com'], names: ['DeepSeek'] },
  'Xiaomi MiMo': { slug: 'xiaomi', domains: ['mi.com', 'xiaomi.com'], names: ['Xiaomi'] },
  'Fireworks AI': { slug: 'fireworks', domains: ['fireworks.ai'], names: ['Fireworks AI'] },
  'Together AI': { slug: 'together', domains: ['together.ai'], names: ['Together AI'] },
  'DeepInfra': { slug: 'deepinfra', domains: ['deepinfra.com'], names: ['DeepInfra'] },
  'Nebius AI': { slug: 'nebius', domains: ['nebius.com'], names: ['Nebius'] },
  'SiliconFlow': { slug: 'siliconflow', domains: ['siliconflow.com', 'siliconflow.cn'], names: ['SiliconFlow'] },
  'Cursor': { slug: 'cursor', domains: ['cursor.com'], names: ['Cursor'] },
  'OpenCode': { slug: 'opencode', domains: ['opencode.ai'], names: ['OpenCode'] },
  'HyperAgent': { slug: 'hyperagent', domains: ['hyperagent.com'], names: ['HyperAgent'] },
  'Crof AI': { slug: 'crof', domains: ['crof.ai'], names: ['Crof AI'] },
  'Wafer AI': { slug: 'wafer', domains: ['wafer.ai'], names: ['Wafer AI'] },
  'Neuralwatt': { slug: 'neuralwatt', domains: ['neuralwatt.com'], names: ['Neuralwatt'] },
  'CommandCode': { slug: 'commandcode', domains: ['commandcode.ai'], names: ['CommandCode'] },
  'Groq': { slug: 'groq', domains: ['groq.com'], names: ['Groq'] },
  'Cohere': { slug: 'cohere', domains: ['cohere.com'], names: ['Cohere'] },
  'Mistral': { slug: 'mistral', domains: ['mistral.ai'], names: ['Mistral AI'] },
  'Perplexity': { slug: 'perplexity', domains: ['perplexity.ai'], names: ['Perplexity'] },
  'Cloudflare': { slug: 'cloudflare', domains: ['cloudflare.com'], names: ['Cloudflare'] },
  'Amazon Bedrock': { slug: 'amazon', domains: ['aws.amazon.com', 'amazon.com'], names: ['Amazon Web Services', 'Amazon'] },
  'Azure': { slug: 'azure', domains: ['azure.microsoft.com', 'microsoft.com'], names: ['Microsoft Azure', 'Microsoft'] },
  'AI21': { slug: 'ai21', domains: ['ai21.com'], names: ['AI21 Labs'] },
  'Cerebras': { slug: 'cerebras', domains: ['cerebras.ai'], names: ['Cerebras'] },
  'SambaNova': { slug: 'sambanova', domains: ['sambanova.ai'], names: ['SambaNova'] },
  'StepFun': { slug: 'stepfun', domains: ['stepfun.ai'], names: ['StepFun'] },
  'Baidu': { slug: 'baidu', domains: ['baidu.com'], names: ['Baidu'] },
  'ByteDance': { slug: 'bytedance', domains: ['bytedance.com', 'byteplus.com'], names: ['ByteDance'] },
  'Tencent Cloud': { slug: 'tencent', domains: ['tencentcloud.com', 'tencent.com'], names: ['Tencent'] },
  'Upstage': { slug: 'upstage', domains: ['upstage.ai'], names: ['Upstage'] },
  'Meta': { slug: 'meta', domains: ['meta.com'], names: ['Meta'] },
  'Deepgram': { slug: 'deepgram', domains: ['deepgram.com'], names: ['Deepgram'] },
  'Voyage AI': { slug: 'voyage', domains: ['voyageai.com'], names: ['Voyage AI'] },
  'Black Forest Labs': { slug: 'bfl', domains: ['bfl.ai', 'blackforestlabs.ai'], names: ['Black Forest Labs'] },
  'Modal': { slug: 'modal', domains: ['modal.com'], names: ['Modal'] },
  'Baseten': { slug: 'baseten', domains: ['baseten.co'], names: ['Baseten'] },
  'CoreWeave': { slug: 'coreweave', domains: ['coreweave.com'], names: ['CoreWeave'] },
  'DigitalOcean': { slug: 'digitalocean', domains: ['digitalocean.com'], names: ['DigitalOcean'] },
  'Crusoe': { slug: 'crusoe', domains: ['crusoe.ai'], names: ['Crusoe'] },
  'io.net': { slug: 'ionet', domains: ['io.net'], names: ['io.net'] },
  'GMICloud': { slug: 'gmicloud', domains: ['gmicloud.ai'], names: ['GMICloud'] },
  'AtlasCloud': { slug: 'atlascloud', domains: ['atlascloud.ai'], names: ['AtlasCloud'] },
  'NVIDIA': { slug: 'nvidia', domains: ['nvidia.com'], names: ['NVIDIA'] },
  'Reka AI': { slug: 'reka', domains: ['reka.ai'], names: ['Reka AI'] },
  'Thinking Machines': { slug: 'thinkingmachines', domains: ['thinkingmachines.ai'], names: ['Thinking Machines'] },
  'Inception Labs': { slug: 'inception', domains: ['inceptionlabs.ai'], names: ['Inception Labs'] },
  'Sakana AI': { slug: 'sakana', domains: ['sakana.ai'], names: ['Sakana AI'] },
  'Poolside': { slug: 'poolside', domains: ['poolside.ai'], names: ['Poolside'] },
  'Relace': { slug: 'relace', domains: ['relace.ai'], names: ['Relace'] },
  'Decart': { slug: 'decart', domains: ['decart.ai'], names: ['Decart'] },
  'Liquid AI': { slug: 'liquid', domains: ['liquid.ai'], names: ['Liquid AI'] },
  'Runway': { slug: 'runway', domains: ['runwayml.com', 'runway.com'], names: ['Runway'] },
  'Krea': { slug: 'krea', domains: ['krea.ai'], names: ['Krea'] },
  'HeyGen': { slug: 'heygen', domains: ['heygen.com'], names: ['HeyGen'] },
  'Fish Audio': { slug: 'fishaudio', domains: ['fish.audio'], names: ['Fish Audio'] },
  'Sourceful': { slug: 'sourceful', domains: ['sourceful.com'], names: ['Sourceful'] },
  'Chutes': { slug: 'chutes', domains: ['chutes.ai'], names: ['Chutes'] },
  'Venice': { slug: 'venice', domains: ['venice.ai'], names: ['Venice'] },
  'Mancer': { slug: 'mancer', domains: ['mancer.tech'], names: ['Mancer'] },
  'NextBit': { slug: 'nextbit', domains: ['nextbit256.com'], names: ['NextBit'] },
  'AkashML': { slug: 'akashml', domains: ['akashml.com', 'akash.network'], names: ['Akash'] },
  'Phala (Redpill)': { slug: 'phala', domains: ['redpill.ai', 'phala.network'], names: ['Phala', 'Redpill'] },
  'Inference.net': { slug: 'inferencenet', domains: ['inference.net'], names: ['Inference.net'] },
  'Novita AI': { slug: 'novita', domains: ['novita.ai'], names: ['Novita AI'] },
  'FriendliAI': { slug: 'friendli', domains: ['friendli.ai'], names: ['FriendliAI'] },
  'Parasail': { slug: 'parasail', domains: ['parasail.io'], names: ['Parasail'] },
  'Open Inference': { slug: 'openinference', domains: ['openinference.ai'], names: ['Open Inference'] },
  'Ionstream': { slug: 'ionstream', domains: ['ionstream.ai'], names: ['Ionstream'] },
  'Darkbloom': { slug: 'darkbloom', domains: ['darkbloom.dev'], names: ['Darkbloom'] },
  'Sail Research': { slug: 'sailresearch', domains: ['sailresearch.com'], names: ['Sail Research'] },
  'Perceptron': { slug: 'perceptron', domains: ['perceptron.inc'], names: ['Perceptron'] },
  'Inceptron': { slug: 'inceptron', domains: ['inceptron.io'], names: ['Inceptron'] },
  'DekaLLM (Cloudeka)': { slug: 'dekallm', domains: ['cloudeka.id', 'cloudeka.ai'], names: ['Cloudeka AI', 'Cloudeka', 'DekaLLM'] },
  'StreamLake': { slug: 'streamlake', domains: ['streamlake.ai'], names: ['StreamLake'] },
  'Aion Labs': { slug: 'aionlabs', domains: ['aionlabs.ai'], names: ['Aion Labs'] },
  'MARA': { slug: 'mara', domains: ['mara.com'], names: ['MARA'] },
  'Nex AGI': { slug: 'nexagi', domains: ['nex-agi.cn', 'nex-agi.com'], names: ['Nex AGI'] },
  'ModelRun (Modular)': { slug: 'modular', domains: ['modular.com'], names: ['Modular'] },
  'Morph': { slug: 'morph', domains: ['morphllm.com'], names: ['Morph'] },
};

export function logoMap() {
  return Object.fromEntries(
    Object.entries(PROVIDER_LOGOS).map(([name, { slug }]) => [name, slug]),
  );
}

export function uniqueSlugs() {
  return [...new Set(Object.values(PROVIDER_LOGOS).map((e) => e.slug))].sort();
}
